name: Data

on:
  schedule:
    - cron:  '0 0,6,9,14 * * *'
    
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: data
        path: data1
    - name: Checkout group data repo
      uses: actions/checkout@v2
      with:
        repository: ShinyGroup/SCTranslationData
        path: data2
    - name: Move files
      run: |
        cp -r data2/data/ data1/
    - name: Commit changes
      run: |
        cd data1
        git add --a
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "##[set-output name=message;]$(git commit -m 'update data')"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: data
        directory: data1
        github_token: ${{ secrets.DATA_TOKEN }}